import { getInsights } from '@/lib/api';
import { TriggerButton } from '@/components/TriggerButton';
import { relativeTime } from '@/lib/utils';

const REPORT_TYPES = ['weekly_report', 'market_brief'] as const;

const TYPE_LABELS: Record<string, string> = {
  weekly_report: 'Weekly Digest',
  market_brief:  'Monthly Brief',
};

const TYPE_STYLES: Record<string, { bg: string; text: string }> = {
  weekly_report: { bg: 'bg-purple-100', text: 'text-purple-700' },
  market_brief:  { bg: 'bg-blue-100',   text: 'text-blue-700' },
};

const STATUS_STYLES: Record<string, string> = {
  draft:     'bg-gray-100 text-gray-600',
  published: 'bg-emerald-100 text-emerald-700',
  sent:      'bg-sky-100 text-sky-700',
};

export default async function ReportsPage() {
  // Fetch weekly reports and monthly briefs (market_brief)
  const [weeklies, monthlies] = await Promise.all([
    getInsights({ type: 'weekly_report', limit: 20 }),
    getInsights({ type: 'market_brief',  limit: 20 }),
  ]);

  const allReports = [...(weeklies.insights ?? []), ...(monthlies.insights ?? [])]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  const weeklyCount  = weeklies.insights?.length ?? 0;
  const monthlyCount = monthlies.insights?.length ?? 0;

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500 mt-1">
            Weekly digests and monthly market briefs generated by the pipeline.
          </p>
        </div>
        <div className="flex gap-3">
          <TriggerButton agentType="report-generator" label="Generate Reports" />
          <TriggerButton agentType="master-scheduler" label="Run Full Pipeline" />
        </div>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-2 gap-4 mb-8">
        <div className="bg-white rounded-lg border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Weekly Digests</p>
          <p className="text-3xl font-bold text-gray-900 mt-1">{weeklyCount}</p>
        </div>
        <div className="bg-white rounded-lg border border-gray-200 p-4">
          <p className="text-sm text-gray-500">Monthly Briefs</p>
          <p className="text-3xl font-bold text-gray-900 mt-1">{monthlyCount}</p>
        </div>
      </div>

      {/* Report list */}
      {allReports.length === 0 ? (
        <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
          <p className="text-gray-400 text-sm">No reports yet. Run the report generator or the full pipeline.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {allReports.map((report) => {
            const typeStyle  = TYPE_STYLES[report.type]  ?? { bg: 'bg-gray-100', text: 'text-gray-600' };
            const typeLabel  = TYPE_LABELS[report.type]  ?? report.type;
            const statusStyle = STATUS_STYLES[report.status] ?? 'bg-gray-100 text-gray-600';

            return (
              <div key={report.id} className="bg-white rounded-lg border border-gray-200 p-5">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-2">
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${typeStyle.bg} ${typeStyle.text}`}>
                        {typeLabel}
                      </span>
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${statusStyle}`}>
                        {report.status}
                      </span>
                      <span className="text-xs text-gray-400">{relativeTime(report.createdAt)}</span>
                    </div>
                    <h2 className="text-sm font-semibold text-gray-900 mb-2">{report.title}</h2>
                    <pre className="text-xs text-gray-600 whitespace-pre-wrap font-mono leading-relaxed bg-gray-50 rounded p-3 max-h-60 overflow-y-auto">
                      {report.body}
                    </pre>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
